sudo: false
language: node_js
node_js:
- '8'
- '10'
install:
- npm i npminstall && npminstall
script:
- npm run ci
after_script:
- npminstall codecov && codecov
env:
  global:
  - secure: "CI3jWCrytRsuj8XJDUXQ6/n/XXT1YyX8rNLZhLSw91vCCghv6ozgu5K/gaZxLUWdscIdoTHbo0TxdhlxlmlC9bxFh+2jXtyfFKmg9BuITEjfYyLr9VO8OT2xQauVkr73OkTgwskADiJCL5vrci879oB5gWcHADGClI1CNa0oaiLB1dCveSgpglsrH3ftsZm8o2wQeZhmtK8zAB9RxRcWQabBU6xuQqxCnQb/FZZfHZNhnVXVAzhuEm9AtFzhMcndpNKY3dAqldU4lm2C3QZbzUG2c6Ga2+5DxnK/+4Y/zpFE0R3rVmipCmVJg+cH49EA+wGX5HsdqG7fwVXH3dKl/CY0JEoyxFO1pfqYkHFmOeNTBQRxM7mTAUP1OGaPZGfnVhgxeCc5CAfz9pc6rGyYyJjOxghkNejarikMpBeoAsNIjjg37bBjVH1qkWJuyj2/6KGzdz/vSaQYUfnkmUhNbW1mfxFux9hH+6ZpYotFbbMsR9yGBS3xIa7In4msLLSkinYN/jdwbccegsZSC8noY8VvjLV48qigwQp6FErFDKuiIYkvX4gKnS71d2z76r5EMUPWuV37mpfH5XeQ0K2kY6ApMJ6vnYzyeresxI4umU6kf8xAJ0bbC2iPSLo54iPGlpAPCkdPz0lqCYMmgp0iyLS4glkq+Nv5GKhKd9EUF60="
