sudo: false
language: node_js
node_js:
- '8'
- '10'
install:
- npm i npminstall && npminstall
script:
- npm run ci
after_script:
- npminstall codecov && codecov
env:
  global:
  - secure: "pM4TQ72otx1LMiAyPZ5kd1fgfanCH7K0FNRA9mzElHUIFMxWXEz6HVSYXgtcTNg1IOI+m9RlhdF9iSp6XKt7zcYiwEVgTYTdeLoH9Xk1ELMPjsHr6JNWcgLnDMYg1TO+vf29R4QZtx6eiROYYXL650tk2dFK6/zkUKN7PT8jjR5xKC6MhiGbkH+QlrPbjSHFGb165+IFfVNb6a6mN+zO5D8CYKtrN5J+BX8nIUjxtONJgQz4qtqBNTy4ywIzhGw9Qn4AJqA6Ecx7CHj59NW4yEpVcRZUoKFfZS0r5LW44M+NjtRa6teuzQARKyyzt9rUW85fYbttIalJmNoevuqgewgRZd3Rk96Jo7HlVR4UGjFMVJ2w/zZe/hkXzcd+9lh4LCs8WVcf47qVP9sx2zvKuFW3l4FqkX+GZXJ3opcytawg5BgOTs4+r0gWRDDrWyFMZW0CTDfrjmrtQ+D9Hg3xur9CWDsKjYqgAWDnTsMd7HsBeH7d3tL9lZcJzOgNnnx2ekX3mFuyfFirrhp/kcj7ecG4TfC3wk3d+hwJBpPExVOt5ECjEAxl9285vRftTnfbrNqJOmiY+4Z2ZhgjPIuPtM2Jg877eH1Wxp+qaJA394c28sto5XFES8eMzxqu3wPR53jrXqXydUgFwpjM0Hgbc8gSAQ8BLLvoah+vYqjmmHQ="
