sudo: false
language: node_js
node_js:
- '8'
- '10'
install:
- npm i npminstall && npminstall
script:
- npm run ci
after_script:
- npminstall codecov && codecov
env:
  global:
  - secure: "WC4m+rF+FXZO2t8t5z8yDKE/lUGh93B7SURNTrxf17L6k29CHmgMUgNevCvdymAqfQuklKyf1aECsLsrUggsj8tkANLU5GfOrrVHOTg+5hh7w5kf7lIwgrMOP6N+7tsYqhXVSCPGkdmaMb26LmDgmaZg0UzqORfGnuN1bivABASCQ18kKSsXlDBo+emcA9hUzZVdZ8fre8DEGscTuti95sBa/IG1FHhaT4kV615c+PiXEL0TVWQJMWFz8R7w0UGZMI/hYF/ifyjeVdWVzZUBt1/vAUlWaA7cHvXziYPcsSJV8xEszI+3tliZ/ccqiIsqkR2+/PKBxM4EvhRvfxoIyYzvGJlOSCUBlV0Z02Su+89Mbm73qd/INJKs/WcTcJGCeQp/dqVbg/HM8umdEMod0oVKCrXSMrLvn6MqhjQmlN0Ppfj2Ba/rzqEy5IT9fe7hHDNY9gfQTmDMBK9QYT0ru19cGqRyNfzbGxKg669lAaPgXDFxt+CoXev7ncNwPo0kZe0gUEWQkX6xHm/GDjcpcsSTMbkuitrsFNmYKbO1Ule7RH+ygT7vc4WaQXKpJ/GhIZS9YH7zS1mse7iACauFuq5mRPQhWwxDkBXLJEDRSotJRzNmtGVxiT9vHGiGVSgzvpDMDZQrwP5+RM/vWSFATt2UoT2yurn+F/DqSfuGEmM=""
